### ISSUE TITLE
external json files prevent scene build in 0.9

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#383]
This test works in 0.8:

http://tangrams.github.io/tangram-frame/?lib=0.8&url=https://raw.githubusercontent.com/tangrams/differ-tests/gh-pages/unit-tests/sources/sources-external-geojson.yaml#13/0.0193/-0.0161

…but fails in 0.9:

http://tangrams.github.io/tangram-frame/?lib=0.9&url=https://raw.githubusercontent.com/tangrams/differ-tests/gh-pages/unit-tests/sources/sources-external-geojson.yaml#13/0.0193/-0.0161

Also, this test works, comparing 0.7 to 0.8:

http://tangrams.github.io/differ/?1=https%3A//github.com/tangrams/differ-tests/blob/gh-pages/unit-tests/sources/sources01.json&2=&lib1=0.7&lib2=0.8&go

But this test fails at "sources-external-json", when comparing 0.8 to 0.9:

http://tangrams.github.io/differ/?1=https%3A//github.com/tangrams/differ-tests/blob/gh-pages/unit-tests/sources/sources01.json&2=&lib1=0.8&lib2=0.9&go

Additionally, creating any new json file at geojson.io and attempting to serve and load it as a source in a scene file prevents the scene from loading at all – white screen, no console output.

**Comment by bcamper** [comment]
Yikes. Looks like it's hanging because the incremental tile build functionality is never completing for empty tiles (which only really happen with non-tiled data sources). Looking into it...

**Comment by bcamper** [comment]
OK I believe this is resolved here https://github.com/tangrams/tangram/commit/58664d9ee767e0ae6cf8078927907f6b1b6ba3e5, and I would like to cut a new Tangram 0.9.1 release for this and other bug fixes. But I want to make sure I test this carefully.

@IvanSanchez - do you happen to have the example scene file you were trying handy for us to test? Alternatively, you can also access the master branch of Tangram directly at https://precog.mapzen.com/tangrams/tangram/master/dist/tangram.debug.js if you want to check yourself.

**Comment by bcamper** [comment]
This looks verified here: http://tangrams.github.io/differ/?1=https%3A//github.com/tangrams/differ-tests/blob/gh-pages/unit-tests/sources/sources01.json&2=&lib1=0.8&lib2=https%3A//precog.mapzen.com/tangrams/tangram/master/dist/tangram.debug.js&go

(Note differences in box size from changes in `vanishing_point` behavior in v0.9.0, but that is expected.)

**Comment by IvanSanchez** [comment]
@bcamper I've pulled and built a fresh copy of the `master` branch, and it still fails for me. :sob: 

I've left my `.yaml` file at https://gist.github.com/IvanSanchez/868241d4cb8d3395ef984ec5b0c0ddac, and my geojson at https://gist.github.com/IvanSanchez/a5bb8ace5333b90dce5ddddb026371cd?short_path=619541a (it's partial data, but still reproduces the bug). I know it fails to build the scene, as the (commented) natural earth layer fails to display when the `walls` layer is uncommented.

**Comment by bcamper** [comment]
Hey @IvanSanchez - I can get your walls polygon to render on this build, example here:

http://tangrams.github.io/tangram-frame/?url=https://gist.githubusercontent.com/anonymous/7e83b778746b91af9f9fd381c6c01441/raw/4de2dda5fcf2326c0a67e2e5d3012f3e305d7520/scene.yaml&lib=https://precog.mapzen.com/tangrams/tangram/master/dist/tangram.debug.js#24/63.41555/10.40676

Let me know if that renders for you? (There may be some precision-related issues from the very high zoom level, but I'm at least getting a red polygon.)

I don't have a reference to your other Natural Earth file, maybe you could post it too? Is it a problem you're experiencing when rendering those two sources together, or were you unable to get this walls polygon to render on its own as well? Something I can see off-hand in your scene file is that your walls layer has `order: 1`, and NE has `order: 3`, which would cause the NE layer to draw on top and maybe obscure the walls layer (actually both orders are commented, but that could be related). Let me know, happy to test with both files if you'd like!

**Comment by bcamper** [comment]
I believe the original issue as described here has been resolved in the released v0.9.1, so I'm closing this issue as is.

However, @IvanSanchez, if you continue to experience issues with your scene, please feel free to either comment here, open a few issue, or reach us on gitter chat, and we'll be glad to help out. Thanks!
